# Generated by Django 2.2.4 on 2019-08-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('image', models.ImageField(default='portfolio_picture/no_image.jpg', upload_to='portfolio_picture/')),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
