# Generated by Django 2.2.4 on 2019-08-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio_app', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=9000)),
                ('address', models.CharField(max_length=2000)),
                ('phone_number', models.CharField(default='+0123456789', max_length=20)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
